import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AppRouterCacheProvider} from "@mui/material-nextjs/v13-appRouter";
import "./globals.css";
import { Container, CssBaseline, ThemeProvider } from "@mui/material";
import darkTheme from "./dark.theme";
import Header from "./header/header";
import Providers from "./providers";
import authenticated from "./auth/authenticated";
import logout from "./auth/logout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
	}: Readonly<{
	children: React.ReactNode;
	}>) {
		const isAuthenticated = await authenticated();
	return (
		<html lang="en">
		<body className={inter.className}>
			<Providers authenticated={isAuthenticated}>
					<CssBaseline />
					<Header logout={logout}/>
					<Container className={isAuthenticated ? "mt-10" : ""}>{children}</Container>
			</Providers> 
		</body>
		</html>
	);
}
